### ISSUE TITLE
Alternative approach

### ISSUE THREAD

**Issue by mrichar1** [Namwanza/divide-numbers-into-even-parts#1]
I saw your solution when I was looking for an efficient way to do this operation - but later came up with an alternative approach:

```
var mod = num % parts
var div = num / parts
var result = Array(mod).fill(div + 1).concat(Array(parts - mod).fill(div))
```

This is much faster (around 3x) as it's not looping and the total amount of comparison and mathematical operations is much lower.

I thought I'd share since it might be useful to you!

**Comment by namwanza** [comment]
Hi Mrichar1;
I will try it out. Thanks

**Comment by namwanza** [comment]
Hi Mrichar1, i tried your solution and it's really good. 
Thanks
